/**
 * Demo files seed data
 * Creates sample files with different security labels, owners, and departments
 * to demonstrate all access control models
 */

export const demoFiles = [
  // Public files (MAC - Level 1)
  {
    _id: 'file_001',
    name: 'Company_Public_Handbook.pdf',
    description: 'Public company handbook accessible to all employees',
    type: 'application/pdf',
    size: 2456789,
    ownerId: 'admin',
    ownerUsername: 'admin',
    classification: 'Public',
    clearanceLevel: 1,
    department: 'All',
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(), // 30 days ago
    updatedAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    permissions: {},
    sharedWith: [],
    tags: ['handbook', 'public', 'policy'],
  },
  {
    _id: 'file_002',
    name: 'Employee_Benefits_Overview.pdf',
    description: 'Overview of employee benefits package',
    type: 'application/pdf',
    size: 1234567,
    ownerId: 'manager1',
    ownerUsername: 'alice_manager',
    classification: 'Public',
    clearanceLevel: 1,
    department: 'HR',
    createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    permissions: {},
    sharedWith: [],
    tags: ['benefits', 'hr', 'public'],
  },

  // Internal files (MAC - Level 2)
  {
    _id: 'file_003',
    name: 'Q4_Financial_Report.xlsx',
    description: 'Quarterly financial report for internal use',
    type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    size: 4567890,
    ownerId: 'manager1',
    ownerUsername: 'alice_manager',
    classification: 'Internal',
    clearanceLevel: 2,
    department: 'Finance',
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    permissions: {},
    sharedWith: [],
    tags: ['finance', 'report', 'internal', 'q4'],
  },
  {
    _id: 'file_004',
    name: 'IT_Infrastructure_Diagram.png',
    description: 'Network infrastructure diagram for IT department',
    type: 'image/png',
    size: 2345678,
    ownerId: 'admin',
    ownerUsername: 'admin',
    classification: 'Internal',
    clearanceLevel: 2,
    department: 'IT',
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    permissions: {},
    sharedWith: [],
    tags: ['it', 'infrastructure', 'diagram', 'internal'],
  },
  {
    _id: 'file_005',
    name: 'HR_Policy_Updates_2024.docx',
    description: 'Updated HR policies for internal review',
    type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    size: 3456789,
    ownerId: 'staff1',
    ownerUsername: 'bob_staff',
    classification: 'Internal',
    clearanceLevel: 2,
    department: 'HR',
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    permissions: {},
    sharedWith: [],
    tags: ['hr', 'policy', 'internal', '2024'],
  },

  // Confidential files (MAC - Level 3)
  {
    _id: 'file_006',
    name: 'Executive_Salary_Data.xlsx',
    description: 'Confidential executive compensation data',
    type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    size: 5678901,
    ownerId: 'manager1',
    ownerUsername: 'alice_manager',
    classification: 'Confidential',
    clearanceLevel: 3,
    department: 'Finance',
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    permissions: {},
    sharedWith: [],
    tags: ['finance', 'salary', 'confidential', 'executive'],
  },
  {
    _id: 'file_007',
    name: 'Security_System_Architecture.pdf',
    description: 'Confidential security system architecture documentation',
    type: 'application/pdf',
    size: 6789012,
    ownerId: 'admin',
    ownerUsername: 'admin',
    classification: 'Confidential',
    clearanceLevel: 3,
    department: 'IT',
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    permissions: {},
    sharedWith: [],
    tags: ['security', 'architecture', 'confidential', 'it'],
  },
  {
    _id: 'file_008',
    name: 'Merger_Acquisition_Plan.docx',
    description: 'Highly confidential merger and acquisition strategy',
    type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    size: 7890123,
    ownerId: 'admin',
    ownerUsername: 'admin',
    classification: 'Confidential',
    clearanceLevel: 3,
    department: 'All',
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    permissions: {},
    sharedWith: [],
    tags: ['merger', 'acquisition', 'confidential', 'strategy'],
  },

  // Files for DAC demonstration (different owners)
  {
    _id: 'file_009',
    name: 'Project_Alpha_Proposal.pdf',
    description: 'Project proposal owned by manager, can be shared',
    type: 'application/pdf',
    size: 3456789,
    ownerId: 'manager1',
    ownerUsername: 'alice_manager',
    classification: 'Internal',
    clearanceLevel: 2,
    department: 'Finance',
    createdAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    permissions: {
      staff1: {
        grantedBy: 'manager1',
        grantedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
        permissions: ['read'],
      },
    },
    sharedWith: ['staff1'],
    tags: ['project', 'proposal', 'finance'],
  },
  {
    _id: 'file_010',
    name: 'Team_Meeting_Notes.docx',
    description: 'Team meeting notes with read/write permissions shared',
    type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    size: 1234567,
    ownerId: 'staff1',
    ownerUsername: 'bob_staff',
    classification: 'Internal',
    clearanceLevel: 2,
    department: 'HR',
    createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    permissions: {
      manager1: {
        grantedBy: 'staff1',
        grantedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
        permissions: ['read', 'write'],
      },
    },
    sharedWith: ['manager1'],
    tags: ['meeting', 'notes', 'hr'],
  },

  // Files for department-based access (RBAC/ABAC)
  {
    _id: 'file_011',
    name: 'Finance_Department_Budget_2024.xlsx',
    description: 'Finance department budget - Finance role required',
    type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    size: 4567890,
    ownerId: 'manager1',
    ownerUsername: 'alice_manager',
    classification: 'Internal',
    clearanceLevel: 2,
    department: 'Finance',
    createdAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
    permissions: {},
    sharedWith: [],
    tags: ['finance', 'budget', '2024'],
  },
  {
    _id: 'file_012',
    name: 'IT_System_Backup_Procedure.pdf',
    description: 'IT department backup procedures',
    type: 'application/pdf',
    size: 2345678,
    ownerId: 'admin',
    ownerUsername: 'admin',
    classification: 'Internal',
    clearanceLevel: 2,
    department: 'IT',
    createdAt: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
    permissions: {},
    sharedWith: [],
    tags: ['it', 'backup', 'procedure'],
  },
  {
    _id: 'file_013',
    name: 'HR_Recruitment_Strategy_2024.docx',
    description: 'HR department recruitment strategy',
    type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    size: 3456789,
    ownerId: 'staff1',
    ownerUsername: 'bob_staff',
    classification: 'Internal',
    clearanceLevel: 2,
    department: 'HR',
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    permissions: {},
    sharedWith: [],
    tags: ['hr', 'recruitment', 'strategy', '2024'],
  },

  // Additional demo files
  {
    _id: 'file_014',
    name: 'Client_Contract_Template.docx',
    description: 'Standard client contract template',
    type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    size: 2345678,
    ownerId: 'manager1',
    ownerUsername: 'alice_manager',
    classification: 'Internal',
    clearanceLevel: 2,
    department: 'Finance',
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    permissions: {},
    sharedWith: [],
    tags: ['contract', 'template', 'finance'],
  },
  {
    _id: 'file_015',
    name: 'System_Administration_Guide.pdf',
    description: 'System administration guide for IT staff',
    type: 'application/pdf',
    size: 5678901,
    ownerId: 'admin',
    ownerUsername: 'admin',
    classification: 'Internal',
    clearanceLevel: 2,
    department: 'IT',
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    permissions: {},
    sharedWith: [],
    tags: ['admin', 'guide', 'it', 'system'],
  },
];

export default demoFiles;
